for i in range(0,6):
        print(f"<div style='border:5px solid black;'>")
        print(f"  <center></br></br>")
        print(f'<h1 ><b>^{{ title{i} }}~</b></h1>')
        print(f"<button type='button' class='collapsible' style='")
        print(f"    background-color:#555555;")
        print(f"    border: none;")
        print(f"    color: white;")
        print(f"    padding: 15px 32px;")
        print(f"    text-align: center;")
        print(f"    text-decoration: none;")
        print(f"    display: inline-block;")
        print(f"    font-size: 16px;")
        print(f"    margin: 4px 2px;")
        print(f"    cursor: pointer;")
        print(f"    border-spacing: 50px;")
        print(f" '>Read more</button>")
        print(f"<div class='content'>")
        print(f"  <p style='font: size 50px;'>^{{ news{i} }}~</p>")
        print(f"</div>")
        print(f"<img src='^{{predicted{i}}}~'width='750'height='200'></img></br>")
        print(f"<p style='font: size 50px;'><b>PREDICTED</b></p>")

        print(f"<img src='^{{bias{i}}}~'width='750'height='200'></img></br>")
        print(f"<p><b>ACTUAL</b></p>")

        print(f"      <div align='left'></br>")
        print(f"<p style='font: size 75px; text-indent: 30px;'><b> Polarity: ^{{ polarity_score{i} }}~</b></p>")
        print(f"<p style='font: size 75px; text-indent: 30px;'><b> Subjectivity:^{{ subjectivity_score{i} }}~</b></p></div></center> </div>")
